"""Packaging and artifact integrity test asserting wheel structure and PEP 561 compliance."""

from __future__ import annotations

import glob
import os
import zipfile

import pytest


@pytest.mark.packaging
def test_wheel_contains_py_typed_and_dynamic_version() -> None:
    """Ensure built wheel package ships py.typed marker and dynamically generated version."""
    wheel_files = glob.glob("dist/ewm_engine-*.whl")
    if not wheel_files:
        pytest.skip("No wheel found in dist/ to inspect (run python -m build first).")

    # Inspect the most recently built wheel
    latest_wheel = max(wheel_files, key=os.path.getmtime)
    with zipfile.ZipFile(latest_wheel, "r") as zf:
        namelist = zf.namelist()

        # 1. PEP 561 py.typed marker MUST be present inside ewm_engine/
        assert "ewm_engine/py.typed" in namelist, (
            f"PEP 561 marker 'ewm_engine/py.typed' missing from wheel {latest_wheel}!"
        )

        # 2. Dynamic version file generated by hatch-vcs MUST be present
        assert "ewm_engine/_version.py" in namelist, (
            f"VCS version file 'ewm_engine/_version.py' missing from wheel {latest_wheel}!"
        )

        # 3. Core package entrypoints must exist
        assert "ewm_engine/__init__.py" in namelist
        assert "ewm_engine/core/state.py" in namelist
        assert "ewm_engine/simulation/engine.py" in namelist

        # 4. Wheel metadata should not bundle tests, benchmarks, or scratch
        for name in namelist:
            assert not name.startswith("tests/"), f"Test file leaked into wheel: {name}"
            assert not name.startswith("benchmarks/"), f"Benchmark leaked into wheel: {name}"
            assert not name.endswith(".pyc"), f"Compiled bytecode leaked into wheel: {name}"
