"""Experimental modules and algorithms for EWM Engine.

WARNING: Everything in this namespace is EXPERIMENTAL. Interfaces, signatures,
and behaviors may change or be removed across releases without deprecation cycles.
"""

from __future__ import annotations

from ewm_engine.core.actions import Intervention
from ewm_engine.dynamics.learned import (
    LearnedDynamics,
    LinearResidualDynamics,
    TransitionDataset,
    TransitionSample,
)
from ewm_engine.experimental.causal import (
    CausalGraph,
    CausalRefutationSuiteResult,
    ConfoundingSensitivityReport,
    EValueResult,
    IdentifiabilityResult,
    InterventionalQueryResult,
    NotIdentifiableResult,
    ObservationalQueryResult,
    PositivityReport,
    RefutationTestResult,
    TwinRolloutResult,
    check_backdoor_identifiability,
    check_positivity_overlap,
    compute_e_value,
    query_interventional,
    query_observational,
    report_confounding_sensitivity,
    run_causal_refutations,
    twin_rollout_counterfactual,
)
from ewm_engine.experimental.dynamics_eval import (
    CalibrationResult,
    DynamicsEvaluationReport,
    InterventionalShiftResult,
    InvariantCheckResult,
    OneStepErrorResult,
    RolloutDivergenceResult,
    collect_transition_dataset,
    evaluate_calibrated_dynamics_gate,
    evaluate_dynamics_model,
    evaluate_interventional_shift,
    evaluate_one_step,
    evaluate_rollout_divergence,
    evaluate_stochastic_calibration,
    from_trajectory,
    select_reliable_horizon,
    symexp,
    symlog,
)
from ewm_engine.experimental.dynamics_torch import TorchNeuralResidualDynamics
from ewm_engine.experimental.graph_dynamics import GraphNeuralDynamics
from ewm_engine.experimental.graph_state import HeterogeneousGraphView
from ewm_engine.experimental.ood import (
    MahalanobisOODDetector,
    OODDetector,
    OODStatus,
    OODStepReport,
    OODTrajectoryReport,
    SupportBoundaryOODDetector,
)
from ewm_engine.experimental.ope import (
    OPEDiagnostics,
    OPEResult,
    evaluate_off_policy,
)
from ewm_engine.experimental.planning import (
    ConstraintPenalizedScorer,
    CVaRScorer,
    ExpectedObjectiveScorer,
    Planner,
    PlanningActor,
    PlanningCandidate,
    PlanningDecision,
    RolloutPlanner,
    RolloutScorer,
    ScorerResult,
    UncertaintyPenalizedScorer,
)
from ewm_engine.experimental.readiness import (
    CategoryScore,
    MetamorphicGateResult,
    MLTestScoreReport,
    ReadinessLevel,
    compute_readiness_report,
    run_metamorphic_regression_gate,
)
from ewm_engine.simulation.mpc import MPCDecisionRecord, RecedingHorizonSimulator

__all__ = [
    "CVaRScorer",
    "CalibrationResult",
    "CategoryScore",
    "CausalGraph",
    "CausalRefutationSuiteResult",
    "ConfoundingSensitivityReport",
    "ConstraintPenalizedScorer",
    "DynamicsEvaluationReport",
    "EValueResult",
    "ExpectedObjectiveScorer",
    "GraphNeuralDynamics",
    "HeterogeneousGraphView",
    "IdentifiabilityResult",
    "Intervention",
    "InterventionalQueryResult",
    "InterventionalShiftResult",
    "InvariantCheckResult",
    "LearnedDynamics",
    "LinearResidualDynamics",
    "MLTestScoreReport",
    "MPCDecisionRecord",
    "MahalanobisOODDetector",
    "MetamorphicGateResult",
    "NotIdentifiableResult",
    "OODDetector",
    "OODStatus",
    "OODStepReport",
    "OODTrajectoryReport",
    "OPEDiagnostics",
    "OPEResult",
    "ObservationalQueryResult",
    "OneStepErrorResult",
    "Planner",
    "PlanningActor",
    "PlanningCandidate",
    "PlanningDecision",
    "PositivityReport",
    "ReadinessLevel",
    "RecedingHorizonSimulator",
    "RefutationTestResult",
    "RolloutDivergenceResult",
    "RolloutPlanner",
    "RolloutScorer",
    "ScorerResult",
    "SupportBoundaryOODDetector",
    "TorchNeuralResidualDynamics",
    "TransitionDataset",
    "TransitionSample",
    "TwinRolloutResult",
    "UncertaintyPenalizedScorer",
    "check_backdoor_identifiability",
    "check_positivity_overlap",
    "collect_transition_dataset",
    "compute_e_value",
    "compute_readiness_report",
    "evaluate_calibrated_dynamics_gate",
    "evaluate_dynamics_model",
    "evaluate_interventional_shift",
    "evaluate_off_policy",
    "evaluate_one_step",
    "evaluate_rollout_divergence",
    "evaluate_stochastic_calibration",
    "from_trajectory",
    "query_interventional",
    "query_observational",
    "report_confounding_sensitivity",
    "run_causal_refutations",
    "run_metamorphic_regression_gate",
    "select_reliable_horizon",
    "symexp",
    "symlog",
    "twin_rollout_counterfactual",
]
